name: Build Executables

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
    
    - name: Clean up Zone.Identifier files
      run: |
        Get-ChildItem -Recurse -Name "*:Zone.Identifier" | ForEach-Object { Remove-Item $_ -Force }
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico --name="File Organizer" file_organizer.py
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: File-Organizer-Windows
        path: dist/File Organizer.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico --name="File Organizer" file_organizer.py
    
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: File-Organizer-Linux
        path: dist/File Organizer

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico --name="File Organizer" file_organizer.py
    
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: File-Organizer-macOS
        path: dist/File Organizer

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          File-Organizer-Windows/File Organizer.exe
          File-Organizer-Linux/File Organizer
          File-Organizer-macOS/File Organizer
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
